% File generated by Facile version 0.53a
%
tic;
global ode_tot_cputime;
global ode_num_calls;
ode_tot_cputime = 0.0;
ode_num_calls = 0;

% initial values (free nodes only)
G0401R = 2.32578151753603;
TG00000 = 1000;
G0401R_TG00000i00 = 0;
TG00001 = 0;
G0401T = 0;
G0401T_TG00000i00 = 0;
G3958R = 0.0827729746752389;
G3958R_TG00001i00 = 0;
G3958T = 0;
G3958T_TG00001i00 = 0;
G0401R_G1770i00 = 0;
G0401R_G1770_TG00000i00 = 0;
G0401T_G1770i00 = 0;
G0401T_G1770_TG00000i00 = 0;
G1770 = 3.78192236963763;
LG0000 = 0.001;
G1770_LG0000i00 = 0;
G0401R_G1770_LG0000i00 = 0;
G0401T_G1770_LG0000i00 = 0;
if exist('ivalues') == 0
ivalues = [G0401R TG00000 G0401R_TG00000i00 TG00001 G0401T G0401T_TG00000i00 G3958R G3958R_TG00001i00 ...
	G3958T G3958T_TG00001i00 G0401R_G1770i00 G0401R_G1770_TG00000i00 G0401T_G1770i00 G0401T_G1770_TG00000i00 G1770 LG0000 ...
	G1770_LG0000i00 G0401R_G1770_LG0000i00 G0401T_G1770_LG0000i00];
end
% rate constants and constant expressions
fb00             = 0.501187233627272;
bb00             = 3.98107170553497;
kp00             = 742.963950759494;
fb01             = 1;
bb01             = 0.251188643150958;
kp01             = 0.001;
bb02             = 0.00398107170553497;
kp02             = 5.15952796467086;
fb02             = 15.8489319246111;
bb03             = 31.6227766016838;
kp03             = 148.943147721724;
bb04             = 0.0316227766016838;
fb03             = 1.99526231496888;
bb05             = 7.94328234724282;
fb04             = 7.94328234724282;
bb06             = 1;
fu00             = 0.83898397503098;
bu00             = 0.0207355491991768;
fu01             = 28.0983198521169;
bu01             = 2.36271606752329;
fu02             = 0.0857888971911124;
bu02             = 4.23051229804568;
fu03             = 2.36537658426553;
bu03             = 0.0018486818187763;
fu04             = 0.313887624670169;
bu04             = 6.62987555067509;
fu05             = 0.24186760968626;
bu05             = 0.377172125723928;
clamp_sink_LG0000 = 4.0;
global ode_rate_constants;
ode_rate_constants = [fb00 bb00 kp00 fb01 bb01 kp01 bb02 kp02 fb02 bb03 kp03 bb04 ...
	fb03 bb05 fb04 bb06 fu00 bu00 fu01 bu01 fu02 bu02 fu03 bu03 ...
	fu04 bu04 fu05 bu05 clamp_sink_LG0000];

% time interval
t0= 0;
tf= 20000;

% call solver routine 
global event_times;
global event_flags;
ode_events = [0 0 0 0 0 0 0];
[t, y, intervals]= G154_I00_ode_event(@ode23s, @G154_I00_odes, [t0:1.0:tf], ivalues, odeset(), ode_events, [500.0], [0.001], [1e-06]);


% map free node state vector names
G0401R = y(:,1); TG00000 = y(:,2); G0401R_TG00000i00 = y(:,3); TG00001 = y(:,4); G0401T = y(:,5); G0401T_TG00000i00 = y(:,6); G3958R = y(:,7); G3958R_TG00001i00 = y(:,8); G3958T = y(:,9); G3958T_TG00001i00 = y(:,10); 
G0401R_G1770i00 = y(:,11); G0401R_G1770_TG00000i00 = y(:,12); G0401T_G1770i00 = y(:,13); G0401T_G1770_TG00000i00 = y(:,14); G1770 = y(:,15); LG0000 = y(:,16); G1770_LG0000i00 = y(:,17); G0401R_G1770_LG0000i00 = y(:,18); G0401T_G1770_LG0000i00 = y(:,19); 





if (ode_num_calls > 0)
  ode_avg_cputime = ode_tot_cputime/ode_num_calls*1000;
  str = sprintf('ODE STATS: num ode calls=%d, tot time=%f, avg time=%fms', ode_num_calls, ode_tot_cputime, ode_avg_cputime);
  disp (str)
end

% issue done message for calling/wrapper scripts
str = sprintf('Facile driver script done (elapsed time %f)',toc);
disp (str)

