% File generated by Facile version 0.53a
%
tic;
global ode_tot_cputime;
global ode_num_calls;
ode_tot_cputime = 0.0;
ode_num_calls = 0;

% initial values (free nodes only)
G0000R = 23.7337612310613;
TG00001 = 0;
G0000R_TG00001i01 = 0;
TG00000 = 9.99999999999999;
G0000R_TG00000i00 = 0;
G0000T = 0;
G0000T_TG00001i01 = 0;
G0000T_TG00000i00 = 0;
G0000R_LG0000i00 = 0;
G0000R_LG0000_TG00001i01 = 0;
G0000R_LG0000_TG00000i00 = 0;
G0000T_LG0000i00 = 0;
G0000T_LG0000_TG00001i01 = 0;
G0000T_LG0000_TG00000i00 = 0;
LG0000 = 0.001;
if exist('ivalues') == 0
ivalues = [G0000R TG00001 G0000R_TG00001i01 TG00000 G0000R_TG00000i00 G0000T G0000T_TG00001i01 G0000T_TG00000i00 ...
	G0000R_LG0000i00 G0000R_LG0000_TG00001i01 G0000R_LG0000_TG00000i00 G0000T_LG0000i00 G0000T_LG0000_TG00001i01 G0000T_LG0000_TG00000i00 LG0000];
end
% rate constants and constant expressions
fb00             = 125.892541179417;
bb00             = 7.94328234724282;
kp00             = 27.5348489224465;
fb01             = 251.188643150958;
bb01             = 0.125892541179417;
kp01             = 0.0317297226293716;
fb02             = 0.0316227766016838;
bb02             = 0.001;
kp02             = 24.056457337915;
fb03             = 15.8489319246111;
bb03             = 0.251188643150958;
kp03             = 598.585372268854;
fb04             = 0.00794328234724282;
bb04             = 125.892541179417;
bb05             = 15.8489319246111;
fu00             = 2.36271606752329;
bu00             = 6.53505529858691;
fu01             = 297448.329825947;
fu02             = 0.0747156423764978;
fu03             = 4.71423833050068;
fu04             = 9406.14208462988;
fu05             = 593487.443152145;
clamp_sink_LG0000 = 4.0;
global ode_rate_constants;
ode_rate_constants = [fb00 bb00 kp00 fb01 bb01 kp01 fb02 bb02 kp02 fb03 bb03 kp03 ...
	fb04 bb04 bb05 fu00 bu00 fu01 fu02 fu03 fu04 fu05 clamp_sink_LG0000];

% time interval
t0= 0;
tf= 20000;

% call solver routine 
global event_times;
global event_flags;
ode_events = [0 0 0 0 0 0 0];
[t, y, intervals]= G234_I00_ode_event(@ode23s, @G234_I00_odes, [t0:1.0:tf], ivalues, odeset(), ode_events, [500.0], [0.001], [1e-06]);


% map free node state vector names
G0000R = y(:,1); TG00001 = y(:,2); G0000R_TG00001i01 = y(:,3); TG00000 = y(:,4); G0000R_TG00000i00 = y(:,5); G0000T = y(:,6); G0000T_TG00001i01 = y(:,7); G0000T_TG00000i00 = y(:,8); G0000R_LG0000i00 = y(:,9); G0000R_LG0000_TG00001i01 = y(:,10); 
G0000R_LG0000_TG00000i00 = y(:,11); G0000T_LG0000i00 = y(:,12); G0000T_LG0000_TG00001i01 = y(:,13); G0000T_LG0000_TG00000i00 = y(:,14); LG0000 = y(:,15); 





if (ode_num_calls > 0)
  ode_avg_cputime = ode_tot_cputime/ode_num_calls*1000;
  str = sprintf('ODE STATS: num ode calls=%d, tot time=%f, avg time=%fms', ode_num_calls, ode_tot_cputime, ode_avg_cputime);
  disp (str)
end

% issue done message for calling/wrapper scripts
str = sprintf('Facile driver script done (elapsed time %f)',toc);
disp (str)

